Import('env')

sources = Split("""
   rotor.cpp
   rotor_factory.cpp
   plugboard.cpp
   """)

env.StaticLibrary('enigma', sources)

SConscript(['tests/SConscript'], exports='env', variant_dir='build', duplicate=0)
